### ISSUE TITLE
无法使得switchMap在子线程中执行

### ISSUE THREAD

**Issue by huyanghu** [chiclaim/awesome_android_rxjava#1]
把 .subscribeOn(Schedulers.io())换成observeOn(Schedulers.io())放在switchMap前,试试
  //@TODO 
                .observeOn(Schedulers.io())
 .switchMap(new Func1<CharSequence, Observable<List<String>>>() {
                    @Override
                    public Observable<List<String>> call(CharSequence charSequence) {
                        appendText(tvContent, "switchMap is main thread : " + (Looper.getMainLooper() == Looper.myLooper()));
                        return searchApi.search(charSequence.toString()).flatMap(new Func1<List<String>, Observable<List<String>>>() {
                            @Override
                            public Observable<List<String>> call(List<String> strings) {
                                //测试searchApi.search是不是默认在子线程中执行.
                                appendText(tvContent, "switchMap flatMap transform : " + (Looper.getMainLooper() == Looper.myLooper()));
                                return Observable.just(strings);
                            }
                        });
                    }
                })

**Comment by huyanghu** [comment]
observeOn() 指定的是它之后的操作所在的线程。因此如果有多次切换线程的需求，只要在每个想要切换线程的位置调用一次 observeOn() 即可。
如:
Observable.just(1, 2, 3, 4) // IO 线程，由 subscribeOn() 指定
    .subscribeOn(Schedulers.io())
    .observeOn(Schedulers.newThread())
    .map(mapOperator) // 新线程，由 observeOn() 指定
    .observeOn(Schedulers.io())
    .map(mapOperator2) // IO 线程，由 observeOn() 指定
    .observeOn(AndroidSchedulers.mainThread) 
    .subscribe(subscriber);  // Android 主线程，由 observeOn() 指定

**Comment by chiclaim** [comment]
关于RxJava可以查看android-sample里
